export const ASSETS = {
  logo: "/images/logo.jpg",
  heroMain: "/images/hero-main.jpg",
  aboutHero: "/images/about-hero.jpg",
  ctaBg: "/images/cta-bg.jpg",
  whyChooseUsBg: "/images/why-choose-us-bg.jpg",
  academicCalendarHero: "/images/academic-calendar-hero.jpg",
  campusHero: "/images/why-choose-us-bg.jpg",
  campus1: "/images/campus-1.jpg",
  campus2: "/images/campus-2.jpg",
  facilities1: "/images/facilities-1.jpg",
  programEarlyYears: "/images/program-early-years.jpg",
  programPrimary: "/images/program-primary.jpg",
  programSecondary: "/images/program-secondary.jpg",
  featureIndividualFocus: "/images/feature-individual-focus.jpg",
  featureLearningCommunities: "/images/feature-learning-communities.jpg",
  featureAcademicExcellence: "/images/feature-academic-excellence.jpg",
  featureCreativeThinking: "/images/feature-creative-thinking.jpg",
  featureExtracurricular: "/images/feature-extracurricular.jpg",
  iconMission: "/images/icon-mission.png",
  iconVision: "/images/icon-vision.png",
  iconPhilosophy: "/images/icon-philosophy.png",
  academicCalendarPdf: "/docs/academic-calendar-2024-2025.pdf",
};

